# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-15 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount_module', '0004_remove_period_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'Countries'},
        ),
        migrations.AddField(
            model_name='period',
            name='status',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
